BEGIN;

DROP TABLE IF EXISTS "club",
"club_has_sponsor",
"game",
"level",
"sponsor",
"tournament",
"tournament_has_club";

CREATE TABLE "level" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NULL
);

CREATE TABLE "sponsor" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NOT NULL,
	"slogan" text NULL
);

CREATE TABLE "club" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "country" TEXT,
  "level_id" INTEGER NOT NULL REFERENCES "level"("id")
);

CREATE TABLE "club_has_sponsor" (
  "club_id" INTEGER NOT NULL REFERENCES "club"("id"),
  "sponsor_id" INTEGER NOT NULL REFERENCES "sponsor"("id"),
  PRIMARY KEY (club_id, sponsor_id)
);

CREATE TABLE "game" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NULL,
	"description" text NULL
);
COMMENT ON TABLE game IS 'Not all sports are available, only those selected by the jury.';

CREATE TABLE "tournament" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NOT NULL,
	"description" text NULL,
	"event_date" date NULL,
  "game_id" INTEGER NOT NULL REFERENCES "game"("id")
);

CREATE TABLE "tournament_has_club" (
 "tournament_id" INTEGER NOT NULL REFERENCES "tournament"("id"),
 "club_id" INTEGER NOT NULL REFERENCES "club"("id"),
 PRIMARY KEY (tournament_id, club_id)
);

COMMIT;